In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [3]:
data = pd.read_csv('customers.csv')
print(data.shape)
print(data.dtypes)
data.head()

(7043, 21)
customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
DataFrame=data.copy()

DataFrame.gender=DataFrame.gender.replace("Male",1)
DataFrame.gender=DataFrame.gender.replace("Female",0)

DataFrame.Partner=DataFrame.Partner.replace("Yes",1)
DataFrame.Partner=DataFrame.Partner.replace("No",0)

DataFrame.Dependents=DataFrame.Dependents.replace("Yes",1)
DataFrame.Dependents=DataFrame.Dependents.replace("No",0)

DataFrame.PhoneService=DataFrame.PhoneService.replace("Yes",1)
DataFrame.PhoneService=DataFrame.PhoneService.replace("No",0)

DataFrame.MultipleLines=DataFrame.MultipleLines.replace("Yes",2)
DataFrame.MultipleLines=DataFrame.MultipleLines.replace("No",1)
DataFrame.MultipleLines=DataFrame.MultipleLines.replace("No phone service",0)

DataFrame.InternetService=DataFrame.InternetService.replace("Fiber optic",2)
DataFrame.InternetService=DataFrame.InternetService.replace("DSL",1)
DataFrame.InternetService=DataFrame.InternetService.replace("No",0)

DataFrame.OnlineSecurity=DataFrame.OnlineSecurity.replace("Yes",2)
DataFrame.OnlineSecurity=DataFrame.OnlineSecurity.replace("No",1)
DataFrame.OnlineSecurity=DataFrame.OnlineSecurity.replace("No internet service",0)

DataFrame.OnlineBackup=DataFrame.OnlineBackup.replace("Yes",2)
DataFrame.OnlineBackup=DataFrame.OnlineBackup.replace("No",1)
DataFrame.OnlineBackup=DataFrame.OnlineBackup.replace("No internet service",0)

DataFrame.DeviceProtection=DataFrame.DeviceProtection.replace("Yes",2)
DataFrame.DeviceProtection=DataFrame.DeviceProtection.replace("No",1)
DataFrame.DeviceProtection=DataFrame.DeviceProtection.replace("No internet service",0)

DataFrame.TechSupport=DataFrame.TechSupport.replace("Yes",2)
DataFrame.TechSupport=DataFrame.TechSupport.replace("No",1)
DataFrame.TechSupport=DataFrame.TechSupport.replace("No internet service",0)

DataFrame.StreamingTV=DataFrame.StreamingTV.replace("Yes",2)
DataFrame.StreamingTV=DataFrame.StreamingTV.replace("No",1)
DataFrame.StreamingTV=DataFrame.StreamingTV.replace("No internet service",0)

DataFrame.StreamingMovies=DataFrame.StreamingMovies.replace("Yes",2)
DataFrame.StreamingMovies=DataFrame.StreamingMovies.replace("No",1)
DataFrame.StreamingMovies=DataFrame.StreamingMovies.replace("No internet service",0)

DataFrame.Contract=DataFrame.Contract.replace("Two year",24)
DataFrame.Contract=DataFrame.Contract.replace("One year",12)
DataFrame.Contract=DataFrame.Contract.replace("Month-to-month",1)

DataFrame.PaperlessBilling=DataFrame.PaperlessBilling.replace("Yes",1)
DataFrame.PaperlessBilling=DataFrame.PaperlessBilling.replace("No",0)

DataFrame.PaymentMethod=DataFrame.PaymentMethod.replace("Electronic check",3)
DataFrame.PaymentMethod=DataFrame.PaymentMethod.replace("Mailed check",2)
DataFrame.PaymentMethod=DataFrame.PaymentMethod.replace("Bank transfer (automatic)",1)
DataFrame.PaymentMethod=DataFrame.PaymentMethod.replace("Credit card (automatic)",0)

DataFrame.TotalCharges=DataFrame.Contract*DataFrame.MonthlyCharges

DataFrame.Churn=DataFrame.Churn.replace("Yes",1)
DataFrame.Churn=DataFrame.Churn.replace("No",0)


DataFrame.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,1,0,1,0,0,1,1,...,1,1,1,1,1,1,3,29.85,29.85,0
1,5575-GNVDE,1,0,0,0,34,1,1,1,2,...,2,1,1,1,12,0,2,56.95,683.40,0
2,3668-QPYBK,1,0,0,0,2,1,1,1,2,...,1,1,1,1,1,1,2,53.85,53.85,1
3,7795-CFOCW,1,0,0,0,45,0,0,1,2,...,2,2,1,1,12,0,1,42.30,507.60,0
4,9237-HQITU,0,0,0,0,2,1,1,2,1,...,1,1,1,1,1,1,3,70.70,70.70,1

In [7]:
print(DataFrame.dtypes)

customerID           object
gender                int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
InternetService       int64
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
Contract              int64
PaperlessBilling      int64
PaymentMethod         int64
MonthlyCharges      float64
TotalCharges        float64
Churn                 int64
dtype: object

In [8]:
for col in DataFrame.columns:
    print(DataFrame[col].value_counts(normalize=True))

4654-ULTTN    0.000142
5501-TVMGM    0.000142
4429-WYGFR    0.000142
5884-GCYMI    0.000142
0334-GDDSO    0.000142
                ...
0562-HKHML    0.000142
3765-JXVKY    0.000142
1834-WULEG    0.000142
5301-GAUUY    0.000142
7989-CHGTL    0.000142
Name: customerID, Length: 7043, dtype: float64
1    0.504756
0    0.495244
Name: gender, dtype: float64
0    0.837853
1    0.162147
Name: SeniorCitizen, dtype: float64
0    0.516967
1    0.483033
Name: Partner, dtype: float64
0    0.700412
1    0.299588
Name: Dependents, dtype: float64
1     0.087037
72    0.051399
2     0.033792
3     0.028397
4     0.024989
        ...
28    0.008093
39    0.007951
44    0.007241
36    0.007099
0     0.001562
Name: tenure, Length: 73, dtype: float64
1    0.903166
0    0.096834
Name: PhoneService, dtype: float64
1    0.481329
2    0.421837
0    0.096834
Name: MultipleLines, dtype: float64
2    0.439585
1    0.343746
0    0.216669
Name: InternetService, dtype: float64
1    0.496663
2    0.286668
0    0.216669
Name: OnlineSecurity, dtype: float64
1    0.438450
2    0.344881
0    0.216669
Name: OnlineBackup, dtype: float64
1    0.439443
2    0.343888
0    0.216669
Name: DeviceProtection, dtype: float64
1    0.493114
2    0.290217
0    0.216669
Name: TechSupport, dtype: float64
1    0.398978
2    0.384353
0    0.216669
Name: StreamingTV, dtype: float64
1    0.395428
2    0.387903
0    0.216669
Name: StreamingMovies, dtype: float64
1     0.550192
24    0.240664
12    0.209144
Name: Contract, dtype: float64
1    0.592219
0    0.407781
Name: PaperlessBilling, dtype: float64
3    0.335794
2    0.228880
1    0.219225
0    0.216101
Name: PaymentMethod, dtype: float64
20.05     0.008661
19.85     0.006389
19.95     0.006247
19.90     0.006247
20.00     0.006105
            ...
114.75    0.000142
103.60    0.000142
113.40    0.000142
57.65     0.000142
113.30    0.000142
Name: MonthlyCharges, Length: 1585, dtype: float64
20.05      0.003976
476.40     0.002982
472.80     0.002982
20.00      0.002840
469.20     0.002840
             ...
25.90      0.000142
2463.60    0.000142
103.80     0.000142
1167.00    0.000142
53.10      0.000142
Name: TotalCharges, Length: 2809, dtype: float64
0    0.73463
1    0.26537
Name: Churn, dtype: float64

In [9]:
print(DataFrame['Churn'].value_counts(normalize=True))

0    0.73463
1    0.26537
Name: Churn, dtype: float64

In [12]:
df_comp = DataFrame.drop(columns="customerID")
df=DataFrame.drop(columns="customerID" and "Churn")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,7590-VHVEG,0,0,1,0,1,0,0,1,1,2,1,1,1,1,1,1,3,29.85,29.85
1,5575-GNVDE,1,0,0,0,34,1,1,1,2,1,2,1,1,1,12,0,2,56.95,683.40
2,3668-QPYBK,1,0,0,0,2,1,1,1,2,2,1,1,1,1,1,1,2,53.85,53.85
3,7795-CFOCW,1,0,0,0,45,0,0,1,2,1,2,2,1,1,12,0,1,42.30,507.60
4,9237-HQITU,0,0,0,0,2,1,1,2,1,1,1,1,1,1,1,1,3,70.70,70.70

In [13]:
y=DataFrame.Churn.copy()
y.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [16]:
data_loyal = df_comp[df_comp['Churn'] == 1].reset_index()
data_churn = df_comp[df_comp['Churn'] == 0].reset_index()

      index  gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0         2       1              0        0           0       2             1
1         4       0              0        0           0       2             1
2         5       0              0        0           0       8             1
3         8       0              0        1           0      28             1
4        13       1              0        0           0      49             1
...     ...     ...            ...      ...         ...     ...           ...
1864   7021       1              0        0           0      12             1
1865   7026       0              0        0           0       9             1
1866   7032       1              1        0           0       1             1
1867   7034       0              0        0           0      67             1
1868   7041       1              1        1           0       4             1

      MultipleLines  InternetService  OnlineSecurity  ...  DeviceProtection  \
0                 1                1               2  ...                 1
1                 1                2               1  ...                 1
2                 2                2               1  ...                 2
3                 2                2               1  ...                 2
4                 2                2               1  ...                 2
...             ...              ...             ...  ...               ...
1864              1                1               1  ...                 1
1865              1                1               1  ...                 1
1866              2                2               1  ...                 1
1867              2                2               2  ...                 2
1868              2                2               1  ...                 1

      TechSupport  StreamingTV  StreamingMovies  Contract  PaperlessBilling  \
0               1            1                1         1                 1
1               1            1                1         1                 1
2               1            2                2         1                 1
3               2            2                2         1                 1
4               1            2                2         1                 1
...           ...          ...              ...       ...               ...
1864            2            2                1        12                 1
1865            1            1                1         1                 1
1866            1            1                1         1                 1
1867            1            2                1         1                 1
1868            1            1                1         1                 1

      PaymentMethod  MonthlyCharges  TotalCharges  Churn
0                 2           53.85         53.85      1
1                 3           70.70         70.70      1
2                 3           99.65         99.65      1
3                 3          104.80        104.80      1
4                 1          103.70        103.70      1
...             ...             ...           ...    ...
1864              3           59.80        717.60      1
1865              1           44.20         44.20      1
1866              3           75.75         75.75      1
1867              0          102.95        102.95      1
1868              2           74.40         74.40      1

[1869 rows x 21 columns]

In [19]:
#np.random.shuffle(data_loyal)
#np.random.shuffle(data_churn)

In [37]:
per_train = 0.8
n_row_loyal = data_loyal.shape[0]
n_row_churn = data_churn.shape[0]

row_loyal = round(per_train*n_row_loyal)
row_churn = round(per_train*n_row_churn)

print(row_loyal)
print(row_churn)
#print(data_churn.shape)
#print(data_loyal.shape)

#il y a bcp plus de churn ici !!!!!!juste

1495
4139
(5174, 21)
(1869, 21)

In [40]:
#j'arrive pas  Ã  selectionner les lignes que je veux veux. je crois que c'est pas conciderÃ© comme un tableau 

#train_loyal = data_loyal[:,:row_loyal]
#test_loyal = data_loyal[:,(n_row_loyal-row_loyal):]

#train_churn = data_churn[:,:row_churn]
#test_churn = data_churn[:,(n_row_churn-row_churn):]

In [ ]:
#np.random.shuffle(train_loyal)
#np.random.shuffle(test_loyal)

#np.random.shuffle(train_churn)
#np.random.shuffle(test_churn)

In [42]:
x_train_loyal = train_loyal.drop(columns="Churn")
x_train_loyal.head()
x_test_loyal = test_loyal.drop(columns="Churn")
x_test_loyal.head()

x_train_churn = train_churn.drop(columns="Churn")
x_train_churn.head()
x_test_churn = test_churn.drop(columns="Churn")
x_test_churn.head()

NameError: name 'train_loyal' is not defined

In [ ]:
y_train_loyal = train_loyal.Churn.copy()
y_train_loyal.head()
y_test_loyal = test_loyal.Churn.copy()
y_test_loyal.head()

y_train_churn = train_churn.Churn.copy()
y_train_churn.head()
y_test_churn = test_churn.Churn.copy()
y_test_churn.head()